config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    registrations: 'registrations',
    sessions: :sessions
  }

  root 'top#index'

  resources :users, only: [:show, :index]

  resources :reactions, only: [:create]

  resources :matching, only: [:index]

  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  after_create_commit { ChatMessageBroadcastJob.perform_later self }
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

has_many :chat_room_users
has_many :chat_messages
has_many :users, through: :chat_room_users

end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord

belongs_to :chat_room
  belongs_to :user

end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"

   enum status: { like: 0, dislike: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reactions
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          validates :name, presence: true

          validates :self_introduction, length: {maximum: 500}

          enum gender: { man: 0, woman: 1 }

          mount_uploader :profile_image, ProfileImageUploader

          def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender])

devise_parameter_sanitizer.permit(:account_update, keys: [:name, :self_introduction, :profile_image])

  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

def create
current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to action: :show, id: chat_room.id
  end



  def show
@chat_room = ChatRoom.find(params[:id])
    @chat_room_user = @chat_room.chat_room_users.where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: @chat_room)
  end

end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
 before_action :authenticate_user!

  def index

    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
    @user = User.find(current_user.id)

  end

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update_attributes(
      status: params[:reaction]
    )
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

   def after_update_path_for(resource)
    user_path(resource)
  end

   def after_sign_up_path_for(resource)
    users_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  protected

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

   # ==========ここから追加する==========
  def index
  end
  # ==========ここまで追加する==========

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ここに追加
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

   def index
    @users = User.where.not(id: current_user.id)
    @user = User.find(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_messages/_chat_message.html.erb
<div class="chat-message">
  <% if chat_message.user.id != current_user.id %>
    <div class="chat-message__partner">
      <% if @chat_room_user.profile_image.url.nil? %>
        <div class="chat-message__partner-default-img"></div>
      <% else %>
        <%= image_tag chat_message.user.profile_image.url, class: "chat-message__partner-img" %>
      <% end %>

      <div class="chat-message__content">
        <%= chat_message.content %>
      </div>
    </div>
  <% else %>
    <div class="chat-message__current-user">
      <div class="chat-message__content main-color-bg">
        <%= chat_message.content %>
      </div>
    </div>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="chat-room-show-page">
  <nav class="navbar navbar-light chat-room__header">
    <%= link_to matching_index_path, class: "nav-item nav-link" do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>

    <div class="chat-room__partner">
      <span class="chat-room__partner-name">
        <%= @chat_room_user.name %>
      </span>

      <% if @chat_room_user.profile_image.url.nil? %>
        <div class="chat-room__partner-default-img"></div>
      <% else %>
        <%= image_tag @chat_room_user.profile_image.url, class: "chat-room__partner-img" %>
      <% end %>
    </div>
  </nav>

  <div id='chat-messages'>
    <%= render @chat_messages %>
  </div>

  <form class="chat-room__message-form">
    <textarea data-behavior="chat_room_speaker" data-chat_room_id="<%= @chat_room.id %>" placeholder="メッセージを入力" class="chat-room__message-form_textarea"></textarea>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechpitMatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matching/index.html.erb
<div class="matching-index-page">
  <%= render "partial/navbar" %>

  <div class="matching">
    <p class="matching-title ml-3">メッセージ</p>
    <p class="matching-num">マッチング中のお相手 <%= @match_users.size %>人</p>

    <div class="matching__list">
      <% unless @match_users.empty? %>
        <% @match_users.each do |user| %>
         <%= link_to chat_rooms_path(params: { user_id: user.id }), method: :post do %>
         <div class="matching__person">

           <% if user.profile_image.url.nil? %>
             <div class="matching__person-default-img"></div>
           <% else %>
             <%= image_tag user.profile_image.url, class: "matching__person-img" %>
           <% end %>

           <div class="matching__person-name">
             <%= user.name %>
           </div>

         </div>
         <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-light">
  <%= link_to users_path, class: "nav-item nav-link", data: { turbolinks: :false } do %>
    <span class="<%= 'active' if current_page?(users_path) %>">
      <i class="fas fa-fire fa-lg inherit"></i>
    </span>
  <% end %>

  <%= link_to matching_index_path, class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(matching_index_path) %>">
      <i class="fas fa-comments fa-lg inherit"></i>
    </span>
  <% end %>

  <%= link_to user_path(@user), class: "nav-item nav-link" do %>
    <span class="<%= 'active' if current_page?(user_path(@user)) || current_page?(edit_user_registration_path) %>">
      <i class="fas fa-user fa-lg inherit"></i>
    </span>
  <% end %>
</nav>

app/views/top/index.html.erb
<div class="jumbotron">
  <div class="container">
    <nav class="navbar navbar-light">
      <a class="navbar-brand text-white">Techpit Match</a>
      <div class="navbar__sign-in-btn">

        <%# この行を編集する%>
        <%= link_to "ログイン", new_user_session_path, class: "btn my-2 my-sm-0 bg-light text-top-color" %>

      </div>
    </nav>
  </div>

  <div class="top-title">
    <h1 class="text-white text-center">
      Swipe Right
    </h1>
  </div>

  <div class="top-authentication text-center">
    <div class="top-authentication__sign-up-btn m-3">

      <%# この行を編集する%>
      <%= link_to "アカウントを作成する", new_user_registration_path, class: "btn text-white" %>

    </div>
    <div class="top-authentication__sign-in-btn m-3">

      <%# この行を編集する%>
      <%= link_to "ログイン", new_user_session_path, class: "btn text-white" %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user-index-page">
  <%= render "partial/navbar" %>

  <div class="swipe">
    <div class="swipe--status">
      <i class="fa fa-times"></i>
      <i class="fa fa-heart"></i>
    </div>

    <div class="swipe--cards">
      <% @users.each do |user| %>
        <div class="swipe--card" id="<%= user.id %>">
          <% if user.profile_image.url.nil? %>
            <div class="profile-default-img"></div>
          <% else %>
            <%= image_tag user.profile_image.url, class: "profile-img" %>
          <% end %>
          <p class="profile-name">
            <%= user.name %>
          </p>
        </div>
      <% end %>
      <div class="no-user">近くにお相手がいません;;</div>
    </div>

    <div class="swipe--buttons">
      <button id="dislike"><i class="fas fa-times fa-2x"></i></button>
      <button id="like"><i class="fas fa-heart fa-2x"></i></button>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="user-show-page">

  <%= render "partial/navbar" %>

  <div class="profile mt-4">
  
    <% if @user.profile_image.url.nil? %>
      <div class="profile-default-img"></div>
    <% else %>
      <%= image_tag @user.profile_image.url, class: "profile-img" %>
    <% end %>

    <div class="profile-name mt-4">
      <%= @user.name %>
    </div>

    <div class="profile-text">
    <%= @user.self_introduction %>
    </div>

  </div>

  <% if current_user.id == @user.id %>
    <div class="user-action">
      <div class="user-action-common">
      <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt fa-2x"></i>
        <% end %>
        <span>ログアウト</span>
      </div>
      <div class="user-action-common">
        <%= link_to edit_user_registration_path do %>
          <i class="fas fa-pencil-alt fa-2x"></i>
        <% end %>
        <span>情報を編集<span>
      </div>
    </div>
  <% end %>

</div>